Paket/urls.py
from django.urls import path, re_path
from django.conf.urls.static import static
from django.conf import settings
from .views import ( DetailPaket, SearchPaket)

app_name='paket'
urlpatterns = [
		re_path(r'^$', SearchPaket.as_view(query_string=False), name='view'),
		re_path(r'^search/', SearchPaket.as_view(query_string=True), name='search'),
		re_path(r'^detail/(?P<slug>[\w-]+)$', DetailPaket.as_view(), name='detail'),
	] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# handler404 = 'Travel.views.handle404'

# handler500 = 'Travel.views.handle404'

Travel/urls.py
from django.conf.urls.static import static
from django.contrib.auth.decorators import login_required
from django.conf import settings
from django.contrib import admin
from django.urls import path, include, re_path
from .views import homeView

urlpatterns = [
    # path('admin/', adminLog),
    path('admin/', admin.site.urls, name='admin'),
    path('', homeView.as_view(), name='home'),
    path('', include('userManage.urls', namespace='akun')),
	path('paket/', include('Paket.urls', namespace='paket')),
	path('checkOut/', include('Transaksi.urls', namespace='transaksi')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = 'Travel.views.handle404'

handler500 = 'Travel.views.handle404'

Paket/models.py
from django.db import models
from django.utils.text import slugify

# Create your models here.
class modelPaket(models.Model):
	nama_paket = models.CharField(max_length=100)
	destinasi = models.CharField(max_length=100)
	about = models.TextField()
	harga = models.IntegerField()
	lama_hari = models.IntegerField()
	tgl_berangkat = models.DateField()
	tgl_dibuat = models.DateField(auto_now=True, editable=False)
	slug = models.SlugField(editable=False)

	def save(self):
		self.slug = slugify(f"{self.nama_paket}")
		super().save()

	def __str__(self):
		return f"{self.id} - {self.nama_paket}"

class imagesPaket(models.Model):
	id_paket = models.ForeignKey('modelPaket',related_name='images', on_delete=models.CASCADE)
	image = models.ImageField(null=True, blank=True)

	def __str__(self):
		return f"{self.id} - {self.id_paket}"

	def getImage(self):
		return self.image.url

Paket/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse, reverse_lazy
from django.views.generic import ListView, DetailView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic.edit import FormMixin
from django.db.models import Q
from .models import modelPaket, imagesPaket
from Transaksi.models import modelTransaksi
from Transaksi.form import TransaksiForm
import datetime


# Create your views here.

class SearchPaket(ListView):
    model = modelPaket
    template_name = 'paket/viewPaket.html'
    context_object_name = 'paket_object'
    extra_context = {
        'title': 'PAKET LIST',
    }
    query_string = None

    def findSeacrh(self):
        url = self.request.GET.get('search', False)
        if url != False:
            dataPaket = []
            self.queryset = self.model.objects.filter(
                Q(nama_paket__icontains=self.request.GET['search']) |
                Q(destinasi__icontains=self.request.GET['search'])
            )
            for x in self.queryset:
                if x.tgl_berangkat > datetime.date.today():
                    print(x.tgl_berangkat)
                    dataPaket.append(x)
                print(len(dataPaket))
            if len(dataPaket) == 0:
                self.extra_context = {
                    'title': 'PAKET LIST',
                    'error': "Data Tidak diTemukan"
                }
                self.queryset = None
                return self.queryset
            else:
                return dataPaket
        else:
            self.query_string = False

    def get_queryset(self):
        if self.query_string:
            data = self.findSeacrh()
            return data
        else:
            dataPaket = []
            for x in self.model.objects.all():
                if x.tgl_berangkat > datetime.date.today():
                    dataPaket.append(x)
            return dataPaket;

    def get(self, *args, **kwargs):
        if self.query_string:
            if self.request.GET.get('search', False) is False:
                return HttpResponseRedirect(reverse('paket:view'))
        return super().get(self.request, *args, **kwargs)


class DetailPaket(FormMixin, DetailView):
    form_class = TransaksiForm
    model = modelPaket
    initial={}
    template_name = 'paket/detailPaket.html'
    extra_context = {
        'title': 'DETAIL',
    }

    def get_initial(self):
        dataPaket = self.model.objects.get(slug=self.kwargs['slug'])
        
        if self.request.user.is_authenticated:
            self.initial={
            'paket':dataPaket.slug,
            'user':self.request.user.email
            }
            return self.initial.copy()
        else:
            return super().get_initial()

Paket/templates/paket/detailPaket.html
{% extends "PaketView.html" %}
{% load static %}
{% load humanize %}

{% block content %}
	
	<main>
		<section class="section-package-content mt-5">
			<div class="container">
			 <div class="row">
				 <div class="row p-0">
					 <nav>
						 <ol class="breadcrumb">
							 <li class="breadcrumb-item">
								 Home
							 </li>
							 <li class="breadcrumb-item">
							  Paket Travel
						  </li>
						  <li class="breadcrumb-item active">
							Details Package
						</li>
						 </ol>
					 </nav>
				 </div>
			 </div>  
		</div>
		
		</section>
	
		<section class="section-package">
			<div class="container">
			  <div class="row">
				<div class="col-lg-8 pl-lg-0">
					<div class="card card-details">
						<h1>{{object.nama_paket}}</h1>
						<p>{{object.destinasi}}	</p>
						<!-- <div class="gallery ml-2">
							{% with object.images.all|first as pertama %}
							<div class="xzoom-container">
								   <img 
									src="{{pertama.getImage}}" 
									class="xzoom"
									id="xzoom-default"
									xoriginal="{{pertama.id}}"
									style="width: 650px;"> 
							</div>
							<div class="xzoom-thumbs mt-2">
								{% for x in object.images.all %}
								<img 
									src="{{x.image.url}}" 
									class="xzoom-gallery"
									width="120"
									xpreview="{{pertama.id}}">
								</a>
								{% endfor %}
							</div>
							{% endwith %}
						</div> -->
					
						
						<div id="carouselImg" class="carousel slide" data-ride="carousel">
							
							<div class="carousel-inner">
								{% for x in object.images.all %}
									{% if forloop.counter == 1 %}
									  <div class="carousel-item active">
										<img class="d-block w-100" src="{{x.image.url}}" alt="First slide">
									  </div>
									  {% else %}
									  	<div class="carousel-item">
											<img class="d-block w-100" src="{{x.image.url}}" alt="First slide">
										</div>
									{% endif %}
								  	
							  {% endfor %}
							</div>
							<a class="carousel-control-prev" href="#carouselImg" role="button" data-slide="prev">
							  <span class="carousel-control-prev-icon" aria-hidden="true"></span>
							  <span class="sr-only">Previous</span>
							</a>
							<a class="carousel-control-next" href="#carouselImg" role="button" data-slide="next">
							  <span class="carousel-control-next-icon" aria-hidden="true"></span>
							  <span class="sr-only">Next</span>
							</a>
							
						  </div>
						<h1>Deskripsi Paket</h1>
						<p class="text-description">{{object.about|linebreaks}}</p>
			  </div>
			  
			</div>
			<div class="col-lg-4">
			  <div class="card card-details card-right">
				  <h2>Trip Informations</h2>
				  <hr>
				  <table class="trip-information">
					  <tr>
						  <td width='50%'>Duration</td>
						  <td width='50%' class="text-right">
							 {{object.lama_hari}} Hari
						  </td>
					  </tr>
					  <tr>
						  <td width='40%'>Price</td>
						  <td width='70%' class="text-right">
						   Rp {{object.harga|intcomma}} / Person
						  </td>
					  </tr>
					  <tr>
						  <td width='50%'>Date of Depature</td>
						  <td width='50%' class="text-right">
							 {{object.tgl_berangkat}}
						  </td>
					  </tr>
				  </table>
		  </div>
		  <div class="join-container">
			  <button data-toggle="modal" data-target="#modalCheckout" class="btn btn-block btn-join-now mt-3 py-2">
				  Join Now
			  </button>
		   </div>
		   {% include "include/modal_checkout.html" %}
	   </div>
	  </div>      
	  </div>
			</div>
		  </section>
	</main>
{% endblock content %}

Paket/templates/paket/search.html
{% extends "PaketView.html" %}
{% load static %}

{% block content %}
	<h2>Home / Travel Package</h2>
	{% if error is not None %}
		<h1 class="text-error">{{error}}</h1>
	{% endif %}
	<br>
	{% for i in object_list %}

		<h4>{{i.nama_paket}}</h4>
		<br>
		{% for pic in img %}
			{% if pic.id_paket == i %}
				<img src="{{pic.url}}">
			{% endif %}
		{% endfor %}

	{% endfor %}
{% endblock content %}

Paket/templates/paket/viewPaket.html
{% extends "PaketView.html" %}
{% load static %}
{% load humanize %}

{% block content %}

<main>
    
    <section class="section-package-content mt-5">
        <div class="container">
         <div class="row">
             <div class="col-sm-6 col-md-4 p-0 ml-3">
                 <nav>
                     <ol class="breadcrumb">
                         <li class="breadcrumb-item">
                             Home
                         </li>
                         <li class="breadcrumb-item active">
                          Paket Travel
                      </li>
                     </ol>
                 </nav>
             </div>
         </div>

		<form action="{% url 'paket:search' %}">
         <div class="input-group">
			<input 
    			class="form-control" 
    			type="text"
    			name="search" 
    			placeholder="Search" 
    			aria-label="Search">
          <div class="input-group-append">
              <span >
				  <button class="btn btn-search" type="submit">
					<i class="fas fa-search icon-color"
                    aria-hidden="true"></i>
				  </button>
                </span>
            </div>
		  </div>
		</form>   
    </div>
    </section>

    <section class="section-package ">
        <div class="container">
          <div class="row">
          {% if error is not None %}
            <div class="text-center">
              <p class="text-center text-error mx-5 my-5">{{error}}</p>
            </div>
         
            
        
            
          {% else %}
            {% for i in paket_object %}
              <div class="col-6 col-md-4  ">
                <div class="card-travel shadow-lg rounded" >
                   
                      {% with i.images.all|first as img_pertama %}
                      <img class="card-img-top" src="{{img_pertama.image.url}}" height="200px" alt="Card image cap">
                      {% endwith %}
                      <div class="card-body card-body-search" height="100px">
                      <h5 class="card-title">{{i.nama_paket}}</h5>
                      <p class="card-text">{{i.destinasi}}</p>
            				  <p class="price-text mt-4">{{i.harga|intcomma}} K / Person</p>
            				  <a href="{% url 'paket:detail' i.slug %}" class="btn btn-details float-right">Details</a>
                    </div>
                  </div>
              </div>
            {% endfor %} 
          {% endif %}
          </div>
        </div>
      </section>
</main>
{% endblock content %}