Paket/urls.py
from django.urls import path, re_path
from django.conf.urls.static import static
from django.conf import settings
from .views import ( DetailPaket, SearchPaket)

app_name='paket'
urlpatterns = [
		re_path(r'^$', SearchPaket.as_view(query_string=False), name='view'),
		re_path(r'^search/', SearchPaket.as_view(query_string=True), name='search'),
		re_path(r'^detail/(?P<slug>[\w-]+)$', DetailPaket.as_view(), name='detail'),
	] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# handler404 = 'Travel.views.handle404'

# handler500 = 'Travel.views.handle404'

Transaksi/urls.py
from django.urls import path, re_path
from django.contrib.auth.decorators import login_required
from django.conf.urls.static import static
from django.conf import settings
from .views import checkOut, DetailCheckOut, DetailSuccess

app_name = 'transaksi'
urlpatterns = [
	re_path(r'^$', login_required(checkOut.as_view()), name='checkOut'),
	re_path(r'^final/$', login_required(DetailCheckOut.as_view()), name='final'),
	re_path(r'^success/$', login_required(DetailSuccess.as_view()), name='success')
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Travel/urls.py
from django.conf.urls.static import static
from django.contrib.auth.decorators import login_required
from django.conf import settings
from django.contrib import admin
from django.urls import path, include, re_path
from .views import homeView

urlpatterns = [
    # path('admin/', adminLog),
    path('admin/', admin.site.urls, name='admin'),
    path('', homeView.as_view(), name='home'),
    path('', include('userManage.urls', namespace='akun')),
	path('paket/', include('Paket.urls', namespace='paket')),
	path('checkOut/', include('Transaksi.urls', namespace='transaksi')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = 'Travel.views.handle404'

handler500 = 'Travel.views.handle404'

userManage/urls.py
from django.conf.urls.static import static
from django.conf import settings
from django.urls import path, include, re_path
from .views import (Login, Logout, createUser)

app_name='akun'

urlpatterns = [
	re_path(r'^login/$', Login.as_view(), name='login'),
	re_path(r'^logout/$', Logout.as_view(), name='logout'),
	re_path(r'^register/$', createUser.as_view(), name='regis')
]

templates/include/css.html
{% load static %}

<link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.min.css' %}">
<link rel="stylesheet" href="{% static 'styles/main.css' %}">
<link rel="stylesheet" href="{% static 'xzoom/xzoom.css' %}">
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.15.1/css/all.css">
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.15.1/css/v4-shims.css">
<link href="https://fonts.googleapis.com/css2?family=PT+Sans+Caption&display=swap" rel="stylesheet">

templates/include/footer.html
{% load static %}

<footer class="section-footer mt-5 mb-4 border-top">
    <div class="container pt-5 pb-5">
        <div class="col-12">
            <div class="row">
                <div class="col-12 col-lg-3">
                    <h5>
                        FEATURES
                    </h5>
                    <ul class="list-unstyled">
                        <li><a href="#">Reviews</a></li>
                        <li><a href="#">Comunity</a></li>
                        <li><a href="#">Social Media Kit</a></li>
                        <li><a href="#">Affiliate</a></li>
                    </ul>
                </div>
                <div class="col-12 col-lg-3">
                    <h5>
                        ACCOUNT
                    </h5>
                    <ul class="list-unstyled">
                        <li><a href="#">Refund</a></li>
                        <li><a href="#">Security</a></li>
                        <li><a href="#">Reward</a></li>
                    </ul>
                </div>
                <div class="col-12 col-lg-3">
                    <h5>
                        COMPANY
                    </h5>
                    <ul class="list-unstyled">
                        <li><a href="#">Carrer</a></li>
                        <li><a href="#">Help Center</a></li>
                        <li><a href="#">Media</a></li>
                    </ul>
                </div>
                <div class="col-12 col-lg-3">
                    <h5>
                        GET CONNECTED
                    </h5>
                    <ul class="list-unstyled">
                        <li><a href="#">Surabaya</a></li>
                        <li><a href="#">Indonesia</a></li>
                        <li><a href="#">081-0387-6554</a></li>
                        <li><a href="#">support@yujalanyu.id</a></li> 
                    </ul>
                </div>
            </div>
        </div>
    </div>
    <div class="container-fluid">
        <div class="row border-top justify-content-center align-items-center pt-4">
            <div class="col-auto text-gray-500 font-weight-light text-center">
              <h2>2021 Copyright YuJalanYu  
                <br> 
                Build in Surabaya 
                <br> Made with 
                <i class="fas fa-heart" style="color: rgb(252, 124, 183);"></i>
              </h2>
            </div>
        </div>
    </div>
  </footer>

templates/include/js.html
{% load static %}
<script src="{% static 'jquery/jquery-3.5.1.min.js' %}"></script>
<script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>
<script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>
<script src="{% static 'xzoom/min.css' %}"></script>

templates/include/modal.html
{% load static %}
 <!-- Modal -->
 <div class="modal fade" id="modalLogin" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <!--Content-->
        <div class="modal-content shadow-sm">
           
                <div class="text-center mr-3 mt-2">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
              </div>
            <!-- </div> -->
            <div class="modal-header justify-content-center border-bottom-0">
              <img src="{% static 'images/logo_modal.png' %}" alt="Logo Modal">
            </div>
        
            <!--Body-->
            
            <div class="modal-body mx-4">
                <!--Body-->
          
                <form class="modal-form" method="POST" action="{% url "akun:login" %}?next={{request.path|urlencode}}">
                    {% csrf_token %}
                    <div class="form-group">
                        <label for="email">Email</label>
                        <input type="text" name="username" class="form-control " placeholder="Username Or Email address">
                    </div>
                    <div class="form-group">
                        <label for="password">Password</label>
                        <input type="password" name="password" class="form-control"  placeholder="Password">
                    </div>
                    <div class="text-center">
                        <button type="submit" class="btn btn-login-modal mb-3 btn-rounded">Masuk</button>
                        <p class="modal-login">Belum Punya Akun ? <a href="{% url "akun:regis" %}">Register</a></p>
                    </div>

                </form>
            </div>
        </div>
    </div>
  </div>

  <div class="modal fade" id="modalRegister" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <!--Content-->
        <div class="modal-content shadow-sm ">
            <!--Header-->
            <div class="text-center mr-3 mt-2">
              <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                  <span aria-hidden="true">&times;</span>
              </button>
            </div>
          <!-- </div> -->
          <div class="modal-header justify-content-center border-bottom-0">
            <img src="{% static "images/logo_modal.png" %}" alt="">
          </div>
            <!--Body-->
            <div class="modal-body mx-4">
                <!--Body-->

                <form class="modal-form">
                    <div class="form-group">
                        <label for="username">Username</label>
                        <input type="text" name="username" class="form-control " placeholder="Masukkan Username Anda">
                    </div>
                    <div class="form-group">
                      <label for="email">Email</label>
                      <input type="email" name="email" class="form-control " placeholder="Masukkan Email Anda">
                  </div>
                    <div class="form-group">
                        <label for="password">Password</label>
                        <input type="password" name="password" class="form-control"  placeholder="Masukkan Password Anda">
                    </div>
                    <div class="form-group">
                      <label for="password">Password</label>
                      <input type="password" name="password" class="form-control"  placeholder="Masukkan Password Anda">
                  </div>
                    <div class="text-center">
                        <button type="submit" class="btn btn-login-modal btn-rounded mb-3">Login</button>
                        <p class="modal-login">Sudah Punya Akun ? <a href="#ModalLogin">Login</a></p>
                    </div>

                </form>
            </div>
        </div>
    </div>
  </div>

templates/include/modal_checkout.html
{% load static %}
{% load humanize %}
<div class="modal fade" id="modalCheckout" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <!--Content-->
        <div class="modal-content shadow-sm ">
            <!--Header-->
            <div class="text-center mr-3 mt-2">
              <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                  <span aria-hidden="true">&times;</span>
              </button>
            </div>
          <!-- </div> -->
          <div class="modal-header border-bottom">
            <h2 class="header-modal-checkout ">Order Summary <img src="{% static "images/Vector.png" %}"</>
          </div>
            <!--Body-->
            <form method="post" action="{% url "transaksi:checkOut" %}">
              {% csrf_token %}
            <div class="modal-body ">
                <div class="container-fluid">
                  <div class="row">
                    <div class="col-md-4 col-sm-6">{{object.nama_paket}}</div>
                    <div class="col-md-6 col-sm-6  price">IDR {{object.harga|intcomma}}
                      {{form.paket}}
                      {{form.user}}
                    </div>
                  </div>
                  <div class="row mt-3">
                    <div class="col-4 col-sm-6">Person</div>
                    <div class="col-4 col-sm-6 input-person ">
                        {# <input type="number" min="1"> #}
                        {{form.jumlah}}
                    </div>
                  
                  </div>
                  <hr class="mt-5">
                  <div class="row total-price">
                    <h2 class="col-4 col-sm-6">Total</h2>
                    <h2 class="col-4 col-sm-6 ml-auto ">IDR. {{object.harga|intcomma}}</h2>
                  </div>
                 <div class="row">
                   <input type="submit" class="btn btn-primary btn-checkout mx-auto" value="BAYAR">
                 </div>
                </div>
            </div>
            </form>
        </div>
    </div>
  </div>

templates/include/navbar-alternate.html
{% load static %}
<nav class="navbar navbar-expand-lg navbar-light shadow-sm">
  <a class="navbar-brand ml-5" href="#">
    <img src="{% static '/images/Logo.png' %}" alt="">
  </a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
    <ul class="navbar-nav ml-auto mr-5 mt-2 mt-lg-0">
      <li class="nav-item">
        <a class="nav-link" href="{% url 'home' %}">Home</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'paket:view' %}">Travel Package</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'home' %}">Testimonials</a>
      </li>
     
    </ul>
    
        <a class="btn btn-login mr-5" href="#">KELUAR</a>
        
    
      
    </form>
   
  </div>
</nav>

templates/include/navbar.html
{% load static %}
<nav class="navbar navbar-expand-lg navbar-light shadow-sm">
  <a class="navbar-brand ml-5" href="{% url "home" %}">
    <img src="{% static '/images/Logo.png' %}" alt="">
  </a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
    <ul class="navbar-nav ml-auto mr-5 mt-2 mt-lg-0">
      <li class="nav-item">
        <a class="nav-link" href="{% url 'home' %}">Home</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'paket:view' %}">Travel Package</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#testimonials">Testimonials</a>
      </li>
     
    </ul>
      {% if user.is_authenticated %}
        <a class="btn btn-login mr-5 " href="{% url "akun:logout" %}">KELUAR</a>
        {% else %}
        <a class="btn btn-login mr-5" href="{% url "akun:login" %}">MASUK</a>
      {% endif %}

    </form>
    {% include 'include/modal.html' %}
  </div>
</nav>